version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - "5444:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
