// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: option.proto

package option

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PollId        string                 `protobuf:"bytes,2,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	VoteCount     int64                  `protobuf:"varint,4,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_option_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Option) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *Option) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Option) GetVoteCount() int64 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

type CreateOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOptionRequest) Reset() {
	*x = CreateOptionRequest{}
	mi := &file_option_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptionRequest) ProtoMessage() {}

func (x *CreateOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_option_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptionRequest.ProtoReflect.Descriptor instead.
func (*CreateOptionRequest) Descriptor() ([]byte, []int) {
	return file_option_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOptionRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *CreateOptionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOptionResponse) Reset() {
	*x = CreateOptionResponse{}
	mi := &file_option_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptionResponse) ProtoMessage() {}

func (x *CreateOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_option_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptionResponse.ProtoReflect.Descriptor instead.
func (*CreateOptionResponse) Descriptor() ([]byte, []int) {
	return file_option_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOptionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsRequest) Reset() {
	*x = ListOptionsRequest{}
	mi := &file_option_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsRequest) ProtoMessage() {}

func (x *ListOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_option_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListOptionsRequest) Descriptor() ([]byte, []int) {
	return file_option_proto_rawDescGZIP(), []int{3}
}

func (x *ListOptionsRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type ListOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*Option              `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsResponse) Reset() {
	*x = ListOptionsResponse{}
	mi := &file_option_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsResponse) ProtoMessage() {}

func (x *ListOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_option_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListOptionsResponse) Descriptor() ([]byte, []int) {
	return file_option_proto_rawDescGZIP(), []int{4}
}

func (x *ListOptionsResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_option_proto protoreflect.FileDescriptor

const file_option_proto_rawDesc = "" +
	"\n" +
	"\foption.proto\x12\x06option\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x06Option\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apoll_id\x18\x02 \x01(\tR\x06pollId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x04 \x01(\x03R\tvoteCount\"B\n" +
	"\x13CreateOptionRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"&\n" +
	"\x14CreateOptionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x12ListOptionsRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"?\n" +
	"\x13ListOptionsResponse\x12(\n" +
	"\aoptions\x18\x01 \x03(\v2\x0e.option.OptionR\aoptions2\xa2\x01\n" +
	"\rOptionService\x12I\n" +
	"\fCreateOption\x12\x1b.option.CreateOptionRequest\x1a\x1c.option.CreateOptionResponse\x12F\n" +
	"\vListOptions\x12\x1a.option.ListOptionsRequest\x1a\x1b.option.ListOptionsResponseB&Z$event-driven/proto/gen/option;optionb\x06proto3"

var (
	file_option_proto_rawDescOnce sync.Once
	file_option_proto_rawDescData []byte
)

func file_option_proto_rawDescGZIP() []byte {
	file_option_proto_rawDescOnce.Do(func() {
		file_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_option_proto_rawDesc), len(file_option_proto_rawDesc)))
	})
	return file_option_proto_rawDescData
}

var file_option_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_option_proto_goTypes = []any{
	(*Option)(nil),               // 0: option.Option
	(*CreateOptionRequest)(nil),  // 1: option.CreateOptionRequest
	(*CreateOptionResponse)(nil), // 2: option.CreateOptionResponse
	(*ListOptionsRequest)(nil),   // 3: option.ListOptionsRequest
	(*ListOptionsResponse)(nil),  // 4: option.ListOptionsResponse
}
var file_option_proto_depIdxs = []int32{
	0, // 0: option.ListOptionsResponse.options:type_name -> option.Option
	1, // 1: option.OptionService.CreateOption:input_type -> option.CreateOptionRequest
	3, // 2: option.OptionService.ListOptions:input_type -> option.ListOptionsRequest
	2, // 3: option.OptionService.CreateOption:output_type -> option.CreateOptionResponse
	4, // 4: option.OptionService.ListOptions:output_type -> option.ListOptionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_option_proto_init() }
func file_option_proto_init() {
	if File_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_option_proto_rawDesc), len(file_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_option_proto_goTypes,
		DependencyIndexes: file_option_proto_depIdxs,
		MessageInfos:      file_option_proto_msgTypes,
	}.Build()
	File_option_proto = out.File
	file_option_proto_goTypes = nil
	file_option_proto_depIdxs = nil
}
