FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server server.go
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .
EXPOSE 9091
CMD ["./server"]
