// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: poll.proto

package poll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Poll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{0}
}

func (x *Poll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Poll) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Poll) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Poll) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Poll) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollRequest) Reset() {
	*x = CreatePollRequest{}
	mi := &file_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollRequest) ProtoMessage() {}

func (x *CreatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollRequest.ProtoReflect.Descriptor instead.
func (*CreatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePollRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePollRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollResponse) Reset() {
	*x = CreatePollResponse{}
	mi := &file_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollResponse) ProtoMessage() {}

func (x *CreatePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollResponse.ProtoReflect.Descriptor instead.
func (*CreatePollResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePollResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollRequest) Reset() {
	*x = GetPollRequest{}
	mi := &file_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollRequest) ProtoMessage() {}

func (x *GetPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollRequest.ProtoReflect.Descriptor instead.
func (*GetPollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{3}
}

func (x *GetPollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Poll          *Poll                  `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollResponse) Reset() {
	*x = GetPollResponse{}
	mi := &file_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollResponse) ProtoMessage() {}

func (x *GetPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollResponse.ProtoReflect.Descriptor instead.
func (*GetPollResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{4}
}

func (x *GetPollResponse) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

type UpdatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePollRequest) Reset() {
	*x = UpdatePollRequest{}
	mi := &file_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePollRequest) ProtoMessage() {}

func (x *UpdatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePollRequest.ProtoReflect.Descriptor instead.
func (*UpdatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePollRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePollRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePollRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdatePollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Poll          *Poll                  `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePollResponse) Reset() {
	*x = UpdatePollResponse{}
	mi := &file_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePollResponse) ProtoMessage() {}

func (x *UpdatePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePollResponse.ProtoReflect.Descriptor instead.
func (*UpdatePollResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePollResponse) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

type DeletePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePollRequest) Reset() {
	*x = DeletePollRequest{}
	mi := &file_poll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePollRequest) ProtoMessage() {}

func (x *DeletePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePollRequest.ProtoReflect.Descriptor instead.
func (*DeletePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,3,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPollRequest) Reset() {
	*x = ListPollRequest{}
	mi := &file_poll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPollRequest) ProtoMessage() {}

func (x *ListPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPollRequest.ProtoReflect.Descriptor instead.
func (*ListPollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{8}
}

func (x *ListPollRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPollRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPollRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ListPollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polls         []*Poll                `protobuf:"bytes,1,rep,name=polls,proto3" json:"polls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPollResponse) Reset() {
	*x = ListPollResponse{}
	mi := &file_poll_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPollResponse) ProtoMessage() {}

func (x *ListPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPollResponse.ProtoReflect.Descriptor instead.
func (*ListPollResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{9}
}

func (x *ListPollResponse) GetPolls() []*Poll {
	if x != nil {
		return x.Polls
	}
	return nil
}

var File_poll_proto protoreflect.FileDescriptor

const file_poll_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"poll.proto\x12\x04poll\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\x04Poll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"K\n" +
	"\x11CreatePollRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"$\n" +
	"\x12CreatePollResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetPollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetPollResponse\x12\x1e\n" +
	"\x04poll\x18\x01 \x01(\v2\n" +
	".poll.PollR\x04poll\"x\n" +
	"\x11UpdatePollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"4\n" +
	"\x12UpdatePollResponse\x12\x1e\n" +
	"\x04poll\x18\x01 \x01(\v2\n" +
	".poll.PollR\x04poll\"#\n" +
	"\x11DeletePollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x0fListPollRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vonly_active\x18\x03 \x01(\bR\n" +
	"onlyActive\"4\n" +
	"\x10ListPollResponse\x12 \n" +
	"\x05polls\x18\x01 \x03(\v2\n" +
	".poll.PollR\x05polls2\xc1\x02\n" +
	"\vPollService\x12?\n" +
	"\n" +
	"CreatePoll\x12\x17.poll.CreatePollRequest\x1a\x18.poll.CreatePollResponse\x126\n" +
	"\aGetPoll\x12\x14.poll.GetPollRequest\x1a\x15.poll.GetPollResponse\x12?\n" +
	"\n" +
	"UpdatePoll\x12\x17.poll.UpdatePollRequest\x1a\x18.poll.UpdatePollResponse\x12=\n" +
	"\n" +
	"DeletePoll\x12\x17.poll.DeletePollRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\bListPoll\x12\x15.poll.ListPollRequest\x1a\x16.poll.ListPollResponseB\"Z event-driven/proto/gen/poll;pollb\x06proto3"

var (
	file_poll_proto_rawDescOnce sync.Once
	file_poll_proto_rawDescData []byte
)

func file_poll_proto_rawDescGZIP() []byte {
	file_poll_proto_rawDescOnce.Do(func() {
		file_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)))
	})
	return file_poll_proto_rawDescData
}

var file_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_poll_proto_goTypes = []any{
	(*Poll)(nil),               // 0: poll.Poll
	(*CreatePollRequest)(nil),  // 1: poll.CreatePollRequest
	(*CreatePollResponse)(nil), // 2: poll.CreatePollResponse
	(*GetPollRequest)(nil),     // 3: poll.GetPollRequest
	(*GetPollResponse)(nil),    // 4: poll.GetPollResponse
	(*UpdatePollRequest)(nil),  // 5: poll.UpdatePollRequest
	(*UpdatePollResponse)(nil), // 6: poll.UpdatePollResponse
	(*DeletePollRequest)(nil),  // 7: poll.DeletePollRequest
	(*ListPollRequest)(nil),    // 8: poll.ListPollRequest
	(*ListPollResponse)(nil),   // 9: poll.ListPollResponse
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_poll_proto_depIdxs = []int32{
	0,  // 0: poll.GetPollResponse.poll:type_name -> poll.Poll
	0,  // 1: poll.UpdatePollResponse.poll:type_name -> poll.Poll
	0,  // 2: poll.ListPollResponse.polls:type_name -> poll.Poll
	1,  // 3: poll.PollService.CreatePoll:input_type -> poll.CreatePollRequest
	3,  // 4: poll.PollService.GetPoll:input_type -> poll.GetPollRequest
	5,  // 5: poll.PollService.UpdatePoll:input_type -> poll.UpdatePollRequest
	7,  // 6: poll.PollService.DeletePoll:input_type -> poll.DeletePollRequest
	8,  // 7: poll.PollService.ListPoll:input_type -> poll.ListPollRequest
	2,  // 8: poll.PollService.CreatePoll:output_type -> poll.CreatePollResponse
	4,  // 9: poll.PollService.GetPoll:output_type -> poll.GetPollResponse
	6,  // 10: poll.PollService.UpdatePoll:output_type -> poll.UpdatePollResponse
	10, // 11: poll.PollService.DeletePoll:output_type -> google.protobuf.Empty
	9,  // 12: poll.PollService.ListPoll:output_type -> poll.ListPollResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_poll_proto_init() }
func file_poll_proto_init() {
	if File_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_proto_goTypes,
		DependencyIndexes: file_poll_proto_depIdxs,
		MessageInfos:      file_poll_proto_msgTypes,
	}.Build()
	File_poll_proto = out.File
	file_poll_proto_goTypes = nil
	file_poll_proto_depIdxs = nil
}
