// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: vote/vote.proto

package vote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	OptionId      string                 `protobuf:"bytes,2,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	mi := &file_vote_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_vote_vote_proto_rawDescGZIP(), []int{0}
}

func (x *CastVoteRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *CastVoteRequest) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *CastVoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_vote_vote_proto protoreflect.FileDescriptor

const file_vote_vote_proto_rawDesc = "" +
	"\n" +
	"\x0fvote/vote.proto\x12\x04vote\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x0fCastVoteRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1b\n" +
	"\toption_id\x18\x02 \x01(\tR\boptionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId2H\n" +
	"\vVoteService\x129\n" +
	"\bCastVote\x12\x15.vote.CastVoteRequest\x1a\x16.google.protobuf.EmptyB\"Z event-driven/proto/gen/vote;voteb\x06proto3"

var (
	file_vote_vote_proto_rawDescOnce sync.Once
	file_vote_vote_proto_rawDescData []byte
)

func file_vote_vote_proto_rawDescGZIP() []byte {
	file_vote_vote_proto_rawDescOnce.Do(func() {
		file_vote_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_vote_proto_rawDesc), len(file_vote_vote_proto_rawDesc)))
	})
	return file_vote_vote_proto_rawDescData
}

var file_vote_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vote_vote_proto_goTypes = []any{
	(*CastVoteRequest)(nil), // 0: vote.CastVoteRequest
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_vote_vote_proto_depIdxs = []int32{
	0, // 0: vote.VoteService.CastVote:input_type -> vote.CastVoteRequest
	1, // 1: vote.VoteService.CastVote:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vote_vote_proto_init() }
func file_vote_vote_proto_init() {
	if File_vote_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_vote_proto_rawDesc), len(file_vote_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_vote_proto_goTypes,
		DependencyIndexes: file_vote_vote_proto_depIdxs,
		MessageInfos:      file_vote_vote_proto_msgTypes,
	}.Build()
	File_vote_vote_proto = out.File
	file_vote_vote_proto_goTypes = nil
	file_vote_vote_proto_depIdxs = nil
}
